# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ots}
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Bharanee Rathna}]
  s.date = %q{2011-05-23}
  s.description = %q{Ruby interface to libots libraries for unix.}
  s.email = %q{deepfryed@gmail.com}
  s.extensions = [%q{ext/extconf.rb}]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "VERSION",
    "ext/ots.c",
    "lib/ots.rb"
  ]
  s.homepage = %q{http://github.com/deepfryed/ots}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.2}
  s.summary = %q{Open Text Summarizer interface for Ruby.}
  s.test_files = [%q{test/ots_test.rb}]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 2.10"])
    else
      s.add_dependency(%q<shoulda>, [">= 2.10"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 2.10"])
  end
end

